version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-node-browsers
    environment:
      PERCY_PARALLEL_TOTAL: 2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set PERCY_NONCE
          command: echo export PERCY_PARALLEL_NONCE=$CIRCLE_WORKFLOW_ID >> $HOME/.circlerc

      - run:
          name: Write Job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - run:
          name: Install dependencies
          command: |
              sudo pip install --upgrade virtualenv
              python -m venv venv || virtualenv venv
              . venv/bin/activate
              pip install -r dev-requirements.txt --quiet
              npm install --ignore-scripts

      - run:
          name: Lint & format
          command: |
              npm run lint:test
              npm run format:test

      - run:
          name: Install dependencies (dash)
          command: |
              git clone --branch devtoolsui git@github.com:plotly/dash.git
              git clone --branch fix-prop-types git@github.com:plotly/dash-core-components.git
              git clone git@github.com:plotly/dash-html-components.git
              git clone git@github.com:plotly/dash-table.git
              . venv/bin/activate
              pip install -e ./dash --quiet
              cd dash-core-components && npm install --ignore-scripts && npm run build && pip install -e . && cd ..
              cd dash-html-components && npm install --ignore-scripts && npm run build && pip install -e . && cd ..
              cd dash-table && npm install --ignore-scripts && npm run build && pip install -e . && cd ..

      - run:
          name: Build
          command: |
              . venv/bin/activate
              npm run build
              pip install -e . --quiet
              pip list | grep dash

      - run:
          name: Run tests
          command: |
              . venv/bin/activate
              python --version
              npm run test:py

      - store_artifacts:
          path: /tmp/artifacts

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
    environment:
      PERCY_ENABLE: 0

  "python-3.7":
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    environment:
      PERCY_ENABLE: 0


workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"
