version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-node-browsers
    environment:
      PERCY_PARALLEL_TOTAL: 2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set PERCY_NONCE
          command: echo export PERCY_PARALLEL_NONCE=$CIRCLE_WORKFLOW_ID >> $HOME/.circlerc

      - run:
          name: Write Job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - run:
          name: Install dependencies
          command: |
              sudo pip install --upgrade pip

      - run:
          name: Install dependencies (transient)
          command: |
              . venv/bin/activate
              pip install -e .
              git clone git@github.com:plotly/dash.git
              pip install -e ./dash
              git clone git@github.com:plotly/dash-core-components.git
              cd dash-core-components && npm i && cd ..
              cd dash-core-components && n build && cd ..
              pip uninstall dash-core-components -y
              pip install -e ./dash-core-components

      - run:
          name: Build
          command: npm run build

      - run:
          name: Lint & format
          command: |
              npm run lint:test
              npm run format:test

      - run:
          name: Run tests
          command: |
              . venv/bin/activate
              python --version
              npm run test:py

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
    environment:
      PERCY_ENABLE: 0

  "python-3.7":
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    environment:
      PERCY_ENABLE: 0


workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"
